// 12 Case Studies — AI in Procurement & Supply Chain (PMGTS).
// One primary case per day plus supplementary cases. Every PROMPT is copy-ready
// and every task links back to the Northwind dossier + AI Lab.
//
// Block shapes (all fields optional): { h, body, bullets:[], prompt, compare:{without:[],with:[]}, note }

export const CASES = [
  /* ===================== DAY 1 ===================== */
  {
    id: "csA", day: 1, kind: "primary", code: "Case A",
    title: "What AI Actually Does — and Why Procurement Must Lead",
    area: "AI Overview · Strategic Role · Ethics & Responsible Use",
    theme: "The moment a procurement team realises AI is not magic — and not the enemy",
    org: "Broadstone Healthcare Supplies",
    profile: "A £380m NHS supply-chain organisation with a 58-person procurement team managing 3,400 suppliers across medical consumables, capital equipment and facilities. The board has asked procurement to 'embrace AI.' Nobody has explained what that means.",
    challenge: "The CPO has been told AI will 'transform procurement.' Her team is anxious, excited and sceptical in equal measure. She needs to make AI concrete, useful and honest — before the team forms the wrong mental model. This case shows how she does it in a single session.",
    blocks: [
      { h: "Act 1 — What is AI, actually?",
        body: "The CPO puts a live LLM on screen and types a prompt. The model returns a structured risk framework in 20 seconds. She asks 'Is this right?', the team spots two gaps, she refines the prompt, the model improves. That exchange IS the lesson.",
        prompt: "You are a procurement risk analyst. I manage 3,400 medical suppliers across consumables, capital equipment and facilities for an NHS supply-chain organisation. Summarise the top five risk categories I should monitor, with one example of what each looks like in practice and one signal that would indicate the risk is rising. Present as a table.",
        note: "AI is software that has learned patterns from enormous amounts of text. It predicts what a useful response looks like. It is not intelligent like a person — it can be wrong, confidently. A very fast, very well-read assistant that works on language. Nothing more, nothing less." },
      { h: "Act 2 — The strategic role",
        body: "The team maps AI uses to two columns: automate (replaces routine work) and augment (helps a person decide better). The CPO shows AI classifying six months of unstructured spend in the time it takes to make tea, then surfacing three suppliers whose terms, delivery and news all worsened in the same quarter — a pattern nobody was tracking.",
        prompt: "You are a senior procurement analyst. Here is data on 12 suppliers: their spend, region, risk rating, single-source status, payment terms, current and prior-quarter on-time delivery, defect rate and lead-time trend. Identify which three show the most concerning combination of signals — considering financial risk, geographic exposure, single-source dependency, payment terms and performance direction. Explain your reasoning in one paragraph each.",
        note: "AI's strategic role is to eliminate the work that should never have required a trained professional — so the professional can focus on judgement, negotiation, relationships and accountability." },
      { h: "Act 3 — The ethics moment",
        body: "A junior buyer asks: 'If we use AI to score our suppliers, do they know? What if the score is wrong and we drop them?' The CPO drafts five rules with the team — using AI to propose a starting point, then having the team critique and own the result.",
        prompt: "You are an AI governance advisor. We are a healthcare supply-chain organisation planning to use AI to assess supplier risk and performance. Propose five plain-English rules that ensure our use of AI is transparent, fair, accountable and secure. Each rule should be a single sentence that a non-technical procurement professional can remember and apply.",
        note: "Ethics in procurement AI is a leadership problem, not an IT problem: be transparent about where AI is used, keep a human accountable for every decision, and never let a model make a call a person cannot explain and defend." },
    ],
    task: "Run the three prompts from this case in AI Chat (or the AI Lab), in sequence. After each, note: (1) what the AI got right, (2) what it missed or got wrong, (3) what you as a professional add that it cannot. This — critique, not just consume — is the core AI skill.",
    lesson: "AI is a powerful, fast, well-read assistant that works on language and patterns. It cannot judge, be accountable or replace the professional's role — but it can eliminate everything that was stopping the professional from doing that role well.",
    metrics: ["Live demo: AI classifies 6 months of spend in 20 seconds", "Team confidence: anxious & confused → informed & ready to act", "5 ethics rules established before any AI tool is deployed"],
  },
  {
    id: "cs1", day: 1, kind: "supplementary", code: "Case 1",
    title: "Spend Analytics — Seeing the Invisible",
    area: "Category Management & Spend Analysis",
    theme: "From quarterly spreadsheet to real-time strategic insight",
    org: "Meridian Industrial Solutions",
    profile: "A £600m manufacturer with 2,800 active suppliers across 14 countries, running three separate ERP systems and a shared-services finance team.",
    challenge: "The team produces a spend report once a quarter. Two analysts take three weeks to extract, clean and reconcile data from three systems. By the time it lands, it reflects decisions already made — maverick spend, compliance gaps and price trends are all seen too late.",
    blocks: [
      { h: "Without AI — the quarterly grind",
        bullets: ["Extract raw data from three ERPs into CSVs", "Manually reconcile name variants ('Acme Ltd' = 'ACME' = 'Acme Limited')", "Apply a taxonomy by reading line descriptions by hand", "Build pivot tables; produce a static PDF; field queries for a week", "By week three the window to act has closed — and it repeats next quarter"],
        note: "Outcome: spend visibility is always three months old; analysts spend 80% of their time wrangling data and 20% on insight." },
      { h: "Step 1 · Connect and classify automatically", body: "AI ingests transactions from all three ERPs continuously and maps each to a taxonomy — resolving name variants, matching by VAT number and payment terms — in minutes, not weeks." },
      { h: "Step 2 · Detect anomalies in real time", body: "The model flags spend that deviates from pattern: a new supplier in a category that already has a preferred one; a cost centre buying off-contract; an invoice 40% above the historic line average." },
      { h: "Step 3 · Interrogate your spend", prompt: "Show me the top ten categories where spend is growing faster than budget, and highlight any where we have a preferred supplier we are underusing." },
      { h: "Step 4 · Run a savings opportunity scan", prompt: "Which suppliers appear in more than one category and could be consolidated? Estimate the volume leverage if we combined them." },
      { h: "Step 5 · Act this week, not next quarter", body: "Category managers get a weekly AI-generated, human-reviewed briefing: a renewal due, a compliance gap, a price trend to hedge.",
        compare: { without: ["3 weeks of data prep", "Maverick spend found after the fact", "Analysts 80% data / 20% insight"], with: ["3 hours of strategic review", "Alerts fire in real time", "Analysts 20% data / 80% decisions"] } },
    ],
    task: "Using the spend extract in your dossier, write a prompt that would surface the top three consolidation opportunities for Northwind. Run it in AI Chat (or the AI Lab) and critique the output.",
    lesson: "AI does not replace the category manager's judgement — it eliminates the data lag that makes that judgement too late.",
    metrics: ["3 weeks → 3 hours for spend reporting", "34% reduction in maverick spend", "80% of analyst time shifted from data to insight"],
  },

  /* ===================== DAY 2 ===================== */
  {
    id: "csB", day: 2, kind: "primary", code: "Case B",
    title: "Supplier Intelligence — From Annual Scorecard to Living Relationship",
    area: "Supplier Relationship Management · Performance Prediction · Collaboration",
    theme: "The annual supplier review that became a weekly early-warning system",
    org: "Keller Precision Engineering",
    profile: "A £220m precision engineering manufacturer supplying aerospace and defence. 14 strategic suppliers provide 80% of critical components. The category team has six people.",
    challenge: "Keller's supplier review is an annual event. Three times in five years, a problem that was visible in the data for months became a crisis — because nobody was watching between annual reviews.",
    blocks: [
      { h: "Without AI — the annual review cycle",
        bullets: ["Jan–Mar: extract delivery + quality data from separate systems, reconcile by hand, build an Excel scorecard of the past 12 months", "Apr: cordial annual review; action items filed", "May–Dec: nothing — reactive operational management only", "Nov: a supplier's OTIF slides 94% → 81% over six weeks; nobody notices until a line is at risk in December"],
        note: "Outcome: six months of deteriorating data and a £340k crisis the annual review never predicted — because it was annual." },
      { h: "Step 1 · Segment the base intelligently",
        body: "AI segments the 14 suppliers on spend, risk, single-source status, performance trend and strategic importance — not spend alone — refreshed quarterly.",
        prompt: "You are a supplier-management expert. Segment these 14 suppliers into Strategic, Important and Routine based on: spend, risk rating, single-source status, 12-month delivery trend and strategic importance. Present as a table with a one-line reason and recommended management approach for each." },
      { h: "Step 2 · Monitor weekly, not annually",
        prompt: "Analyse this supplier performance data for the past 8 weeks. For each supplier identify whether performance is improving, stable, declining or at risk. Flag any supplier where two or more metrics have moved in the wrong direction in the same period. Present at-risk suppliers first with the specific data points that triggered the flag." },
      { h: "Step 3 · Predict problems before they become crises",
        prompt: "Based on this supplier's trend over 12 weeks — OTIF declining from 94% to 81%, lead-time variability increasing, two missed acknowledgement SLAs — assess the risk level and suggest three questions to ask in a conversation this week. Also identify external signals (financial, news, sub-tier) to check before the call." },
      { h: "Step 4 · Prepare a better supplier conversation",
        prompt: "Draft a professional agenda and opening statement for a proactive supplier performance conversation. Context: OTIF has declined from 94% to 81% over six weeks. We want to understand the root cause, not apportion blame, and agree a recovery plan. Tone: collaborative, evidence-based, forward-looking. Include three diagnostic questions to distinguish a capacity, sub-tier or management issue." },
      { h: "Step 5 · Model the recovery options",
        prompt: "A strategic supplier has a sub-tier material shortage causing delivery delays. Model three options: (A) we hold a 6-week buffer of finished component — cost and risk; (B) we help the supplier qualify an alternative sub-tier — timescale and cost; (C) we adjust our production schedule to absorb a 3-week delay — operational impact. Recommend the lowest-cost option that protects production continuity." },
      { h: "The collaboration play",
        body: "With trust rebuilt, Keller shares a rolling 12-week forecast; the supplier shares weekly capacity and sub-tier stock. AI integrates both and flags any mismatch before it bites.",
        prompt: "Design a data-sharing protocol between a precision manufacturer and a strategic supplier. Specify: what each party shares, frequency, format, how data is used, and two things to agree up front (confidentiality and what the data may not be used for). Keep it practical for an £18m/year relationship.",
        compare: { without: ["Review cycle: annual", "Problem detected: week 8 at 81% OTIF", "£340k crisis cost"], with: ["Continuous weekly monitoring", "Caught week 2 at 91% OTIF", "Crisis avoided"] } },
    ],
    task: "Using the supplier performance data in the Northwind dossier, run the Step 2 monitoring prompt adapted for Northwind's five key suppliers. Identify the at-risk supplier, write the Step 3 prompt to diagnose it, then write the agenda for a proactive conversation.",
    lesson: "Supplier management without AI is an annual event. With AI it becomes a continuous relationship — catching the signals that were always there, early enough to act collaboratively rather than reactively.",
    metrics: ["Review cycle: annual → weekly", "Detection: week 8 (81%) → week 2 (91%)", "Crisis cost avoided: £340k"],
  },
  {
    id: "cs2", day: 2, kind: "supplementary", code: "Case 2",
    title: "Supplier Risk — From Blind Spot to Early Warning",
    area: "Supplier Relationship Management & Risk",
    theme: "The same disruption, two very different responses",
    org: "Vertex Aerospace Components",
    profile: "A tier-1 aerospace supplier with 120 critical single-source components, a £240m supply base and a zero-tolerance delivery standard from its OEM customers.",
    challenge: "Vertex depends on a single-source SE-Asian supplier for an £18m/year precision component. It has always delivered. Nobody is monitoring it. A financial stress event hits the supplier's market — within six weeks it will miss a critical delivery, halting Vertex's line for 11 days at £2.4m.",
    blocks: [
      { h: "Path A — No AI",
        bullets: ["Wk 1: supplier's accounts show deteriorating liquidity — nobody at Vertex sees it", "Wk 3: a sub-tier raw-material delivery is missed — no system flags it", "Wk 5: late-delivery notice arrives; emergency sourcing begins too late", "Wk 6: production stops — 11 days lost, £2.4m, emergency air freight + rushed backup qualification"],
        note: "Outcome: £2.4m direct cost, OEM relationship damage, six months of board scrutiny." },
      { h: "Path B — With AI · Step 1: monitor financial health continuously", body: "A risk AI scans public filings, credit data and news for all 120 critical suppliers. In week 1 it detects a 3-notch credit downgrade and a sector-liquidity news article." },
      { h: "Step 2 · Early-warning alert fires", body: "Alert: 'Supplier X downgraded. Two sector peers missed deliveries in 30 days. Recommended: request a financial update and activate contingency review.'" },
      { h: "Step 3 · AI assists the supplier conversation", prompt: "Draft a professional message to this supplier requesting a financial health update and a capacity assurance for our next six orders, framing it as a routine risk-management step rather than a vote of no confidence." },
      { h: "Step 4 · Scenario modelling", body: "The team asks: 'If this supplier misses delivery in week 6, what is our exposure and our options?' AI cross-references lead times, inventory, alternatives and air-freight cost to return a ranked contingency plan." },
      { h: "Step 5 · Pre-position, do not panic", body: "The team quietly pre-orders a four-week buffer from the alternative. The supplier stabilises; the buffer is absorbed into stock.",
        compare: { without: ["£2.4m reactive cost", "11 days production lost", "Board scrutiny for months"], with: ["£85k precautionary cost", "Production uninterrupted", "Early warning 5 weeks ahead"] } },
    ],
    task: "Using the performance and supplier data in the Northwind dossier, identify which supplier you would put on AI-assisted monitoring first, and write the prompt that would generate the early-warning brief for that supplier.",
    lesson: "AI does not predict the future — it ensures you see the signals that were always there, early enough to act.",
    metrics: ["£2.4m avoided cost", "11 days of lost production prevented", "Early warning: 5 weeks before the event"],
  },

  /* ===================== DAY 3 ===================== */
  {
    id: "cs3", day: 3, kind: "primary", code: "Case 3",
    title: "Contract Intelligence — Reading 5,000 Contracts Overnight",
    area: "Contract Lifecycle Management",
    theme: "Turning a contract backlog into an active risk register",
    org: "Calloway Building Services",
    profile: "A facilities management group managing 5,200 active supplier contracts across cleaning, security, engineering and specialist services. The legal and commercial team has four people.",
    challenge: "An audit reveals 31% of contracts have lapsed into evergreen status. Liability clauses have never been systematically reviewed. Nobody knows which contracts auto-renew in the next 90 days. The team cannot read 5,200 contracts manually.",
    blocks: [
      { h: "Step 1 · Ingest and extract", body: "AI reads all 5,200 contracts (PDF and Word) and extracts structured data: parties, start/end dates, auto-renewal clause, notice period, liability cap, termination rights, SLA/penalty terms, indexation, data-processing terms." },
      { h: "Step 2 · Build the risk register automatically", body: "AI flags every contract with: (a) renewal due within 90 days, (b) uncapped liability, (c) no termination right, (d) missing data-processing clauses, (e) evergreen status." },
      { h: "Step 3 · Interrogate the portfolio", prompt: "Which contracts renew automatically in the next 60 days, and for which ones does the notice period mean we must act this week? List them ranked by annual value and show the notice deadline for each." },
      { h: "Step 4 · Identify the dangerous clauses", prompt: "Show me all contracts where liability is uncapped or where the liability cap is less than the annual contract value. For each, summarise the specific clause and suggest what a reasonable cap would be based on the contract value." },
      { h: "Step 5 · Draft the remediation", prompt: "Draft a professional letter to this supplier opening a renegotiation of the liability clause. Frame it as a routine commercial review, not a dispute. Keep it under 150 words and offer two alternative cap structures." },
      { h: "Step 6 · Monitor ongoing", body: "A weekly scan flags renewals due, contracts where a supplier's risk profile has changed, and new uploads missing required clauses.",
        compare: { without: ["Four people, three months of manual review", "Prioritised by value alone — a £7m SaaS contract with light data clauses (a compliance timebomb) is missed"], with: ["5,200 contracts reviewed in 48 hours", "31 flagged for urgent action — the team focuses on the 31, not the 5,200"] } },
    ],
    task: "Using the contract extract in the Northwind dossier, write the prompt you would send the AI to identify the three contracts requiring the most urgent commercial action this month. Include what data points you want in the response.",
    lesson: "Contract AI does not negotiate for you — it ensures you never again miss a deadline, a dangerous clause or a value-recovery opportunity buried in documents nobody has time to read.",
    metrics: ["5,200 contracts reviewed in 48 hours", "31 urgent actions vs 4 found manually", "£1.2m recovered from missed indexation"],
  },
  {
    id: "cs4", day: 3, kind: "supplementary", code: "Case 4",
    title: "Negotiation Intelligence — Walking in Better Prepared",
    area: "Negotiation & Supplier Commercials",
    theme: "The negotiator who used AI as their prep coach",
    org: "Harrington Packaging Group",
    profile: "A consumer goods packaging supplier renegotiating a £32m annual paper and board contract with a dominant tier-1 supplier.",
    challenge: "The category manager has 48 hours to prepare. The supplier has indicated a 12% price increase citing raw-material costs. The instinct is to push back — but the evidence is missing. (Traditionally: 2 days, contradictory indices, a gut-feel 6% walk-away, ends up accepting 9%.)",
    blocks: [
      { h: "Step 1 · Build the market context", prompt: "You are a commodity analyst. Summarise the movement in European pulp and paper board indices over the last 12 months, the current supply/demand balance, and the three main drivers of any price movement. Indicate whether a 12% increase is consistent with market conditions." },
      { h: "Step 2 · Understand the supplier's position", prompt: "You are a commercial analyst. This supplier has publicly reported a 3% increase in input costs for paper and board in their latest earnings call. Their operating margin has expanded by 2 percentage points year on year. Given this, what is a credible maximum pass-through they could justify to a customer, and what leverage does the customer hold?" },
      { h: "Step 3 · Prepare the counter-arguments", prompt: "You are a negotiation coach. I am facing a 12% price increase demand on a £32m paper and board contract. My evidence: market indices show 4-6% input cost increase; the supplier's own margin has expanded; I represent 8% of their UK volume. Give me the four strongest counter-arguments and a one-sentence reply to each likely supplier response." },
      { h: "Step 4 · Set the anchors and walk-away", prompt: "Based on the above, suggest an opening position, a realistic target, and a walk-away point, with a one-line rationale for each. What concession could I offer that costs me little but the supplier values (e.g. extended payment terms, volume commitment)?" },
      { h: "Step 5 · Prepare the opening statement", prompt: "Draft a professional, confident two-paragraph opening statement for a contract renegotiation where I am challenging a 12% price increase. I want to be collaborative, not adversarial, but make clear I have done my homework." },
    ],
    task: "Using the Meridian Steel contract scenario (£88m, ends 2026, uncapped price index), write the AI prompt sequence you would use to prepare for the renegotiation. Use the prompt builder in the AI Lab, or paste straight into AI Chat.",
    lesson: "AI is the best preparation coach you have ever had — available at 11pm the night before the meeting, with no ego and access to more data than any colleague.",
    metrics: ["Preparation time: 2 days → 4 hours", "Outcome: 3.8% vs instinct-based 9%", "Value protected: ~£1.6m/year"],
  },

  /* ===================== DAY 4 ===================== */
  {
    id: "cs5", day: 4, kind: "primary", code: "Case 5",
    title: "Demand Forecasting — From Gut Feel to Dynamic Intelligence",
    area: "Demand Planning & Inventory Optimisation",
    theme: "Releasing £18m of trapped working capital",
    org: "Thornton Consumer Products",
    profile: "A £400m FMCG manufacturer with 340 SKUs, six distribution centres and a demand-planning team of eight. Forecast accuracy averages 61%. Annual inventory write-offs are £11m.",
    challenge: "The team forecasts with 13-month rolling averages and intuition for new lines. Promotions are guessed, seasonality applied by rule of thumb, and one safety-stock formula is applied uniformly across all SKUs and sites.",
    blocks: [
      { h: "Diagnose · Step 1: read the demand history", body: "AI analyses three years of sales and segments SKUs by demand pattern — fast/stable, seasonal, promotional, lumpy/slow, new/tail — each needing a different method. The old single average served all five badly.",
        prompt: "Analyse this demand history and segment the SKUs by demand pattern. For each segment, explain which forecasting method is most appropriate and estimate the accuracy improvement achievable. Flag the ten SKUs with the worst forecast accuracy and the highest inventory holding." },
      { h: "Diagnose · Step 2: the true cost of the current approach", prompt: "For our highest-error SKUs, calculate the average excess inventory days and the estimated write-off risk. Rank the SKUs by 'cost of forecast error' — excess stock cost plus lost-sales cost where service failures occurred." },
      { h: "Prescribe · Step 3: the right model per segment", body: "Exponential smoothing for fast movers; ML with weather and event calendars for seasonal; promotion-uplift models for promotional lines; reorder-point optimisation for slow movers." },
      { h: "Act · Step 4: dynamic safety stock per SKU per site", body: "Instead of one blanket rule, AI sets the optimal buffer for each of 340 SKUs across six sites from forecast error, lead-time variability and service target. Some buffers go up; most go down." },
      { h: "Act · Step 5: the weekly planner briefing", prompt: "Based on last week's sales and the current forecast, which SKUs are at risk of stockout in the next 14 days and which are at risk of excess in the next 30 days? List actions by priority — expedite, reduce next order, or hold." },
      { h: "Review · Step 6: human planner approves", body: "AI recommendations are a starting point, not instructions. Planners apply commercial context — a promotion just confirmed, a competitor out of stock — before approving.",
        compare: { without: ["8 people, 13-month averages, gut feel", "Accuracy 61%, write-offs £11m", "70% time on data / 30% decisions"], with: ["AI segmentation, model selection, dynamic stock", "Accuracy 78%, write-offs £4m", "30% time on data / 70% decisions"] } },
    ],
    task: "Using the demand snapshot in the Northwind dossier, write a diagnosis prompt for the AI that identifies which categories have the worst cost of forecast error and recommends where to start. Then write the prescription prompt for the worst category.",
    lesson: "Better forecasting does not just reduce write-offs — it releases working capital, improves service, and frees people for the decisions that actually require a human.",
    metrics: ["Forecast accuracy: 61% → 78%", "Write-offs: £11m → £4m", "Working capital released: £18m"],
  },
  {
    id: "cs6", day: 4, kind: "supplementary", code: "Case 6",
    title: "Logistics Intelligence — The Route Optimisation Problem",
    area: "Logistics & Transportation Management",
    theme: "What takes a team three hours takes AI three seconds",
    org: "Denholm Distribution Services",
    profile: "A 3PL operating 340 vehicles from 12 depots, making 18,000 deliveries per week across the UK. A team of 24 dispatchers builds routes manually every morning.",
    challenge: "Each morning 24 dispatchers spend three hours building routes by eye. Fleet utilisation is 71%, failed deliveries 6.8%, fuel and driver costs rising, and customer ETAs are vague four-hour windows.",
    blocks: [
      { h: "Without AI — the 3am planning session",
        bullets: ["Group deliveries by geography on a map, by eye", "Assign rounds by driver familiarity; three routes change before the first lorry leaves", "Lorries depart 71% full (loads split by geography, not cubic/weight)", "Customer asks 'when?' at 10am — a four-hour window and a guess", "6.8% of deliveries fail, ~£60 each to re-deliver"] },
      { h: "Step 1 · AI builds all 340 routes overnight", body: "The engine ingests tomorrow's 18,000 orders, vehicle capacities, shift patterns, road-speed and traffic data, time windows and emission zones — and builds 340 optimised routes by 1am." },
      { h: "Step 2 · Multi-constraint optimisation", body: "It simultaneously minimises distance, fuel, overtime, failed deliveries, emission-zone penalties and load imbalance — hundreds of millions of combinations no human can solve optimally." },
      { h: "Step 3 · Dispatch reviews exceptions, not routes", body: "Dispatchers arrive to a 12-item exception list (a changed window, two sick drivers, one vehicle down). The 340 standard routes are already done." },
      { h: "Step 4 · Live tracking and dynamic re-routing", body: "If a driver runs 25 minutes late, the last three stops are auto-resequenced to recover time and customers get an updated ETA by text." },
      { h: "Step 5 · Predictive failed-delivery prevention", body: "The evening before, AI flags deliveries likely to fail ('customer missed 3 of last 5 attempts — recommend a morning call'). Five calls, two failures prevented." },
    ],
    task: "Using the Northwind logistics snapshot (£120m spend, 87% on-time, 72% utilisation), write a prompt asking the AI to identify the three highest-impact logistics improvements and estimate the financial and carbon benefit of each.",
    lesson: "Route optimisation is a constraint-satisfaction problem with billions of solutions. AI does not do this better than humans — it does it in a dimension humans cannot operate in.",
    metrics: ["Fleet utilisation: 71% → 88%", "Failed deliveries: 6.8% → 2.1%", "Annual saving: £4.2m (fuel, labour, re-delivery)"],
  },
  {
    id: "cs9", day: 4, kind: "supplementary", code: "Case 9",
    title: "The Control Tower — Seeing the Chain Before It Breaks",
    area: "Supply Chain Visibility & Resilience",
    theme: "The Red Sea disruption — two supply chains, two outcomes",
    org: "Westbrook Electronics vs Ashfield Industrial",
    profile: "Two manufacturers with similar chains, both sourcing 60% of components from East Asia through the Red Sea. In Q1 2024 the crisis adds 14 days to transit and doubles shipping rates overnight.",
    challenge: "Same disruption, two responses: one with no real-time visibility, one with an AI control tower.",
    blocks: [
      { h: "Without AI — Westbrook (no visibility)",
        bullets: ["Day 1: a carrier re-routing email lands in a coordinator's inbox", "Day 3–5: the team manually calls six forwarders to find which of 34 shipments are affected", "Day 7: discovers two critical shipments will be 18 days late; Line 3 shuts in 12 days", "Day 10: emergency air freight at 8× sea rate — £380k; 6 days of disruption"] },
      { h: "Step 1 · Detect before the carrier calls", body: "Ashfield's control tower monitors shipping news, carrier AIS data and port congestion. At 6am on Day 1 it spots vessels re-routing from Bab-el-Mandeb and cross-references its 34 in-transit shipments." },
      { h: "Step 2 · Instant impact assessment", body: "By 8am: '12 of your 34 shipments use Red Sea routing. 3 carry critical components. Revised ETAs: +18 days (2), +11 days (1). Production impact: Line 2 at risk from Day 14.'" },
      { h: "Step 3 · Generate the options", prompt: "Given the revised ETAs, model three response options: (A) air-freight the two critical shipments — cost and production impact; (B) draw down on safety stock — when does production go at risk; (C) partial air freight of highest-criticality items only — cost and days protected. Recommend the lowest-cost option that protects production continuity." },
      { h: "Step 4 · Decide in 2 hours, not 10 days", body: "Option C is approved; air freight booked by 10am Day 1. A proactive update goes to commercial before any customer asks; the board report is AI-generated from live data in 20 minutes." },
      { h: "Step 5 · Monitor the recovery", body: "The tower tracks all 34 shipments daily, updates ETAs as the Cape route settles, and notifies production planning of revised availability automatically.",
        compare: { without: ["Decision time: 10 days", "Emergency cost: £380k", "Production disruption: 6 days"], with: ["Decision time: 2 hours", "Emergency cost: £120k", "Production disruption: 0 days"] } },
    ],
    task: "Northwind has four ERPs and no single view of in-transit inventory. Write a prompt asking the AI to design a pragmatic control tower using data Northwind already holds — the first three visibility flows to connect and the early-warning alert that would deliver the most value.",
    lesson: "Supply chain resilience is not about carrying more inventory — it is about having enough warning to use the inventory and options you already have.",
    metrics: ["Decision time: 10 days → 2 hours", "Emergency cost: £380k → £120k", "Production disruption: 6 days → 0"],
  },

  /* ===================== DAY 5 ===================== */
  {
    id: "cs10", day: 5, kind: "primary", code: "Case 10",
    title: "The AI-Enabled Procurement Function — A Transformation Roadmap",
    area: "Procurement Strategy & Organisational Transformation",
    theme: "From transactional to strategic — the five-year AI journey",
    org: "Crestline Consumer Group",
    profile: "A £1.4bn consumer goods business. Procurement has 65 people and manages £620m of addressable spend. Two years ago the CPO told the board: 'We are a transactional function. We will be a strategic one.' This is how AI made it possible.",
    challenge: "Turning that ambition into a sequenced, value-proven roadmap — foundations first, automation last — without betting the function on hype.",
    blocks: [
      { h: "Phase 1 — Foundation (Year 1): clean the data, prove the value",
        bullets: ["AI spend analytics: classify £620m in 48 hours; surface £42m of off-contract tail", "AI contract extraction: read 3,800 contracts; 67 auto-renewals in 90 days; £2.1m indexation recovered", "Supplier-risk monitoring pilot for the top 80 suppliers"],
        compare: { without: ["Manual spend reports, unknown contract risk, reactive supplier management"], with: ["Real-time spend visibility, proactive contracts, early-warning risk"] },
        note: "Value: £6.2m first-year, 15 people freed from data processing. AI role: analyst — data work at a scale no team can match." },
      { h: "Phase 2 — Augment (Year 2): AI assists every decision",
        bullets: ["AI negotiation prep built into category planning", "Demand-forecast AI across the top 40 categories; dynamic safety stock", "Scope 3 moved from spend-based to activity-based for the top 30 suppliers"],
        compare: { without: ["Gut-feel negotiation, blanket inventory rules, Scope 3 a guess"], with: ["Evidence-backed negotiation, per-SKU inventory, credible Scope 3"] },
        note: "Value: £9.4m additional, forecast accuracy +18pts, Scope 3 accepted by SBTi. AI role: co-pilot beside every significant decision." },
      { h: "Phase 3 — Automate (Year 3): routine work runs itself",
        bullets: ["AI buying agent for tail spend: 190,000 transactions/year handled autonomously", "Three-way matching automated: 91% touchless", "AI scorecards replace manual quarterly reviews"],
        compare: { without: ["Buyers processing 120 orders/day; finance matching invoices by hand"], with: ["Buyers handle exceptions only; matching automatic; scorecards always current"] },
        note: "Value: £7.8m additional, buyer capacity ≈ 12 FTEs redirected to strategy. AI role: agent — whole processes within governed guardrails." },
      { h: "Phase 4 — Transform (Years 4–5): the strategic function the board asked for",
        bullets: ["Control tower live: real-time visibility across tiers", "AI in new-product development: supplier selection and cost modelling from day one", "A validated Scope 3 number in the annual report", "65-person team: 20 strategic, 15 analytical, 10 commercial, 20 operations — zero 'data processors'"],
        compare: { without: ["Transactional function: managing paper, chasing POs, retrospective reports"], with: ["Strategic function: shaping decisions, leading sustainability, managing risk proactively"] },
        note: "Five-year value: £68m. Investment: £8.2m. ROI: 729%. AI role: infrastructure — the foundation everyone works on top of." },
    ],
    task: "Using your Opportunity Backlog from the week, sequence your own organisation's AI roadmap across the four phases. Use AI Chat (or the AI Lab) to generate a one-page board summary making the case for Year 1 investment, modelled on the Crestline story.",
    lesson: "AI transformation in procurement is not a technology project — it is a business transformation enabled by technology. It succeeds when it starts from goals, not tools.",
    metrics: ["Five-year value: £68m", "Investment: £8.2m · ROI: 729%", "Team: 0 data processors, 100% value-adding"],
  },
  {
    id: "cs7", day: 5, kind: "supplementary", code: "Case 7",
    title: "Scope 3 Intelligence — Making Sustainability Measurable",
    area: "Sustainable Procurement & ESG",
    theme: "From a spend-based estimate to a credible reduction roadmap",
    org: "Renwell Energy Systems",
    profile: "A £800m renewable energy equipment manufacturer with net zero by 2035 and a Scope 3 target of −60% by 2030. The current Scope 3 figure is a spend-based estimate the team calls 'a guess we are not proud of.'",
    challenge: "84% of the footprint sits in the supply chain, but Renwell cannot tell the board which suppliers, categories or product lines are the hotspots. The spend-based figure won't satisfy SBTi or customer due diligence.",
    blocks: [
      { h: "Step 1 · From spend-based to activity-based", body: "AI cross-references purchase volumes with IPCC/Ecoinvent and supplier-disclosed factors to produce an activity-based figure per category — far more accurate than spend × a sector average.",
        prompt: "Using our spend and purchase volumes by material category, and applying standard industry emission factors, estimate our Scope 3 emissions by category. Flag where we have actual supplier data versus industry-average assumptions, and note the confidence level for each category." },
      { h: "Step 2 · Identify the hotspots (the 15% that drives 60%)", prompt: "Rank our supply categories by Scope 3 emissions. Which categories and which specific suppliers drive the highest emissions? Show the top 10 as a proportion of total Scope 3. Also calculate: if we achieved a 30% emissions reduction from just the top 5 suppliers, what would be the effect on our total Scope 3 figure?" },
      { h: "Step 3 · Prioritise supplier engagement", body: "AI segments suppliers into Tier 1 (high emissions, willing — collaborate), Tier 2 (high emissions, not engaged — contractual requirements) and Tier 3 (low emissions — share best practice).",
        prompt: "Based on these supplier emissions profiles and their likely ability to reduce emissions (inferred from their region, category and size), produce a prioritised engagement plan. For Tier 1 suppliers, suggest three specific reduction levers for each. For Tier 2, suggest the contract clause we should introduce at next renewal." },
      { h: "Step 4 · Model the reduction pathway", prompt: "Model three decarbonisation scenarios for our Scope 3: (A) current trajectory, (B) engagement with top 15 suppliers and a 25% reduction each, (C) full supplier transition to renewable energy for manufacturing. Show the Scope 3 trajectory to 2030 for each, and identify the gap to our 60% target." },
      { h: "Step 5 · Embed in sourcing decisions", body: "AI adds a carbon score alongside price and quality in every tender, so a slightly dearer but far cleaner supplier can be shown to have a lower 'total cost including carbon liability.'" },
      { h: "Step 6 · Produce the board report", body: "AI generates the quarterly dashboard — Scope 3 by category, supplier progress, trajectory to 2030, plain-English narrative — reviewed by the sustainability team before it goes up." },
    ],
    task: "Using the Northwind emissions snapshot and supplier data, write the AI prompt to identify the three suppliers to engage first and the single fastest Scope 3 reduction action available. Then write a follow-up prompt asking how to avoid greenwashing in how Northwind reports the reduction.",
    lesson: "You cannot manage what you cannot measure. AI makes Scope 3 measurement credible, specific and actionable — turning a compliance burden into a competitive advantage.",
    metrics: ["Accuracy: ±40% estimate → ±8% activity-based", "Hotspots: 15 suppliers = 62% of Scope 3", "On track for −60% by 2030 (was 'unknown')"],
  },
  {
    id: "cs8", day: 5, kind: "supplementary", code: "Case 8",
    title: "The Buying Agent — Autonomous Tail-Spend Management",
    area: "Agentic AI & Process Automation",
    theme: "From 200,000 manual transactions to autonomous buying with guardrails",
    org: "Castleton Manufacturing Group",
    profile: "An industrial manufacturer processing 200,000 supplier transactions a year. The bottom 40% by value (tail spend) is £95m across 2,200 suppliers. A buyer processes ~120 low-value orders a day.",
    challenge: "Buyers spend 60% of their time on orders under £500. Processing one order costs £48 — a 24% overhead on a £200 order — while strategic categories go under-resourced.",
    blocks: [
      { h: "The manual process", bullets: ["Requester submits a form/email", "Buyer checks supplier + budget code, raises a PO, chases acknowledgement, monitors delivery", "Three-way match fails 22% of the time, needing manual fixing", "Cost to process: £48; 18 minutes each; then on to the next of 120"] },
      { h: "Bounded autonomy — what the agent may do", bullets: ["Only approved catalogue suppliers", "Max order value £2,500 per transaction", "Only tail-spend categories (MRO, stationery, standard consumables)", "Budget code must exist with headroom", "Any exception goes to a human buyer immediately"] },
      { h: "Step 1 · Request in plain language", body: "'I need 20 boxes of medium nitrile gloves for the Coventry plant by Thursday.' The agent classifies it (MRO, tail, ~£180), confirms it is in bounds and proceeds." },
      { h: "Step 2 · Select supplier and price", body: "It queries the catalogue, picks the compliant supplier with the better delivery date, confirms price is in range and raises the PO in the ERP." },
      { h: "Step 3 · Monitor and chase", body: "It sends the order confirmation and a chase trigger 24h before the required date; if no confirmation, it follows up and notifies the requester." },
      { h: "Step 4 · Three-way match and payment", body: "On receipt it matches goods-receipt to PO and invoice; if it matches it approves payment, if not it raises a query and flags a human." },
      { h: "Step 5 · Humans handle only exceptions", body: "Buyers review a daily list of 8–12 exceptions — 90 minutes versus 9.6 hours of routine processing. 94% of transactions run autonomously.",
        compare: { without: ["Cost £48/order, 18 min each", "Buyers 40% on strategic work", "22% match-failure firefighting"], with: ["Cost £6/order", "Buyers 90% on strategic work", "94% autonomous, 6% human exceptions"] } },
    ],
    task: "Design the guardrail framework for a tail-spend buying agent at Northwind. Set the scope (which categories), the value threshold, the approval triggers, the access it is allowed (which systems), and the stop controls. Use the bounded-autonomy model from this case.",
    lesson: "Agentic AI is not about removing people — it is about removing the work that should never have required a person in the first place.",
    metrics: ["Processing cost: £48 → £6 per order", "Buyer time on strategy: 40% → 90%", "Annual saving: £8.4m on £95m tail spend"],
  },
];

export const CASE_IDS = CASES.map((c) => c.id);
